parameters:
  kapitan:
    compile:
    - input_paths:
      - components/mysql/main.jsonnet
      input_type: jsonnet
      output_path: manifests
      output_type: yaml
    - input_paths:
      - scripts
      input_type: jinja2
      output_path: scripts
    - input_paths:
      - docs/mysql/README.md
      input_type: jinja2
      output_path: .
      output_type: yaml
    validate:
    - type: kubernetes
      output_paths:
      - manifests/mysql_secret.yml
      kind: secret # temporarily replaced with 'deployment' during test
      version: 1.14.0 # optional, defaults to 1.14.0
    - type: kubernetes
      output_paths:
      - manifests/mysql_service_jsonnet.yml
      - manifests/mysql_service_simple.yml
      kind: service
      version: 1.14.0
  mysql:
    image: mysql:latest
    storage: 10G
    storage_class: standard
    users:
      root:
        password: ?{gpg:targets/${target_name}/mysql/password|randomstr|base64}
        password_sha256: ?{gpg:targets/${target_name}/mysql/password_sha256|reveal:targets/${target_name}/mysql/password|sha256|base64}
        password_sha256_subvar: ?{gpg:targets/${target_name}/mysql/subvars@var2.password_sha256}
        password_subvar: ?{gpg:targets/${target_name}/mysql/subvars@var1.password}
